version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE: review_organization
    networks:
      springboot-tutorial-mysql-net:

  springboot-tutorial:
    container_name: springboot-tutorial
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-tutorial-mysql-net:
    restart: on-failure

networks:
  springboot-tutorial-mysql-net:
